const Event = require('../models/Event')
const Payment = require('../models/Payment')
const PaymentAudit = require('../models/PaymentAudit')
const Ticket = require('../models/Registration')
const User = require('../models/User')
const QRCode = require('qrcode')
const Razorpay = require('razorpay')
const crypto = require('crypto')
const { emitToOrganizer, emitToEvent } = require('../socket')
const { generateTicketQR } = require('../utils/qrGenerator')
const { paymentLogger } = require('../utils/logger')
const mongoose = require('mongoose')

let razorpay = null

if (process.env.RAZORPAY_KEY_ID && process.env.RAZORPAY_KEY_SECRET) {
  razorpay = new Razorpay({
    key_id: process.env.RAZORPAY_KEY_ID,
    key_secret: process.env.RAZORPAY_KEY_SECRET,
  })
  console.log('Razorpay initialized ✓')
} else {
  console.warn('Razorpay keys missing — payment routes disabled')
}

// Remove in-memory auditLogs - use PaymentAudit model + logger

// Helper: Standard response
const sendStandardResponse = (
  res,
  success,
  message,
  data = {},
  error = null,
) => {
  res.status(success ? 200 : 400).json({
    success,
    message,
    data,
    error,
  })
}

// Helper: Create audit log
const createAuditLog = async (
  action,
  userId,
  eventId,
  data = {},
  paymentId = null,
) => {
  try {
    await PaymentAudit.create({
      paymentId,
      eventId,
      userId,
      webhookEventId: data.webhookEventId || null,
      webhookEventType: data.eventType || 'manual',
      action,
      status: data.status || 'info',
      ipAddress: data.ip || 'unknown',
      razorpayPayload: data.payload
        ? JSON.stringify(data.payload).slice(0, 1000)
        : null,
    })
    paymentLogger.logPaymentEvent(action, { userId, eventId, paymentId, data })
  } catch (err) {
    paymentLogger.logPaymentEvent(action, { userId, eventId, paymentId }, err)
  }
}

// Generate unique ticket ID (legacy)
const generateTicketId = () =>
  `TKT-${Date.now()}-${Math.random().toString(36).substr(2, 9).toUpperCase()}`

// Helper used for test UPI flow: create a verified registration with QR code
const generateTicket = async ({ payment, event, userId }) => {
  // Create registration; ticketId & digital signature will be generated by pre-save hook
  let registration = await Ticket.create({
    event: event._id,
    user: userId,
    paymentId: payment._id,
    amount: payment.amount,
    paymentStatus: 'verified',
    paymentMethod: 'upi',
    upiId: event.paymentDetails?.upiId || event.organizerUpiId || '',
    utrNumber: payment.referenceId,
    status: 'paid',
    attendeeInfo: {},
  })

  // Ensure we have the generated ticketId before creating QR
  registration = await Ticket.findById(registration._id)

  const qrPayload = {
    ticketId: registration.ticketId,
    eventId: String(event._id),
    userId: String(userId),
  }

  const qrCode = await QRCode.toDataURL(JSON.stringify(qrPayload), {
    width: 300,
    margin: 2,
  })

  registration.qrCode = qrCode
  await registration.save()

  // Increment event registered count
  await Event.findByIdAndUpdate(event._id, { $inc: { registered: 1 } })

  return registration
}

// SUBMIT PAYMENT PROOF (Checkout "I Have Paid")
// TEST-FRIENDLY: immediately marks payment as verified and generates a ticket.
const submitPaymentProof = async (req, res) => {
  try {
    const { eventId, transactionId, orderRef } = req.body
    const userId = req.user.id

    if (!eventId || !transactionId) {
      return res.status(400).json({ message: 'Missing payment data' })
    }

    const event = await Event.findById(eventId)
    if (!event) {
      return res.status(404).json({ message: 'Event not found' })
    }

    const amount =
      typeof event.ticketPrice === 'number' && event.ticketPrice > 0
        ? event.ticketPrice
        : event.price

    // create payment record (immediately verified for testing)
    const payment = await Payment.create({
      event: eventId,
      user: userId,
      amount,
      currency: 'INR',
      method: 'upi',
      status: 'verified',
      referenceId: String(transactionId).trim(),
      notes: orderRef || undefined,
    })

    // create ticket/registration
    const registration = await generateTicket({
      payment,
      event,
      userId,
    })

    return res.json({
      success: true,
      message: 'Payment verified',
      registration,
    })
  } catch (error) {
    console.error('Payment submit error:', error)
    res.status(500).json({ message: 'Payment processing failed' })
  }
}

// PROCESS PAYMENT - Creates ticket with pending status, waits for organizer verification
const processPayment = async (req, res) => {
  try {
    const { eventId, attendeeInfo, referenceId, screenshot } = req.body
    const userId = req.user.id

    console.log('PROCESS PAYMENT BODY:', req.body)

    // Validate required fields
    if (!eventId) {
      return res.status(400).json({ message: 'Event ID is required' })
    }

    // Get event
    const event = await Event.findById(eventId)
    if (!event) {
      return res.status(404).json({ message: 'Event not found' })
    }

    const isFree = !event.price || event.price === 0

    // Check if user already has a ticket for this event
    let ticket = await Ticket.findOne({
      user: userId,
      event: eventId,
    })

    // If ticket exists and is already paid, return error
    if (
      ticket &&
      (ticket.status === 'paid' || ticket.status === 'checked_in')
    ) {
      return res.status(400).json({
        message: 'You already have a ticket for this event',
        ticketId: ticket.ticketId,
      })
    }

    // Create ticket with PENDING status (not paid yet!)
    if (!ticket) {
      const ticketId = generateTicketId()
      ticket = new Ticket({
        ticketId,
        user: userId,
        event: eventId,
        status: 'pending', // IMPORTANT: Starts as pending
        attendeeInfo: attendeeInfo || {},
      })
      await ticket.save()
      console.log('Created pending ticket:', ticketId)
    }

    // For free events, directly verify
    if (isFree) {
      // Generate QR code
      const qrCode = await QRCode.toDataURL(ticket.ticketId, {
        width: 300,
        margin: 2,
      })

      // Update ticket to paid
      ticket.status = 'paid'
      ticket.qrCode = qrCode
      await ticket.save()

      // Update event registered count
      await Event.findByIdAndUpdate(eventId, {
        $inc: { registered: 1 },
      })

      // Emit event
      emitToEvent(eventId, 'ticketActivated', { ticketId: ticket.ticketId })
      emitToOrganizer(event.organiser.toString(), 'ticketPurchased', {
        ticketId: ticket.ticketId,
        eventId,
        userId,
      })

      createAuditLog('FREE_TICKET_CREATED', userId, eventId, {
        ticketId: ticket.ticketId,
      })

      return res.status(201).json({
        success: true,
        ticket,
        message: 'Registration successful!',
      })
    }

    // For PAID events: Create payment with PENDING status
    const paymentAmount = event.price

    // Check for existing pending payment
    const existingPayment = await Payment.findOne({
      ticket: ticket._id,
      status: 'pending',
    })

    if (existingPayment) {
      return res.status(400).json({
        message: 'Payment already submitted, waiting for verification',
        paymentId: existingPayment._id,
        ticketId: ticket.ticketId,
        status: 'pending',
      })
    }

    // Validate referenceId for paid events
    if (!referenceId) {
      return res
        .status(400)
        .json({ message: 'Payment reference ID is required for paid events' })
    }

    // Create payment with PENDING status
    const payment = new Payment({
      event: eventId,
      user: userId,
      ticket: ticket._id,
      amount: paymentAmount,
      method: 'upi',
      status: 'pending', // IMPORTANT: Starts as pending
      referenceId: referenceId,
      screenshot: screenshot || '',
    })

    await payment.save()
    console.log('Created pending payment:', payment._id)

    // Emit to organizer about new payment
    emitToOrganizer(event.organiser.toString(), 'paymentSubmitted', {
      ticketId: ticket.ticketId,
      paymentId: payment._id,
      eventId,
      amount: paymentAmount,
      userId,
    })

    createAuditLog('PAYMENT_SUBMITTED', userId, eventId, {
      ticketId: ticket.ticketId,
      paymentId: payment._id,
      amount: paymentAmount,
    })

    // Return ticket and payment info
    res.status(201).json({
      success: true,
      ticket,
      payment,
      message:
        'Payment submitted successfully! Waiting for organizer verification.',
    })
  } catch (error) {
    console.error('Process payment error:', error)
    res
      .status(500)
      .json({ message: 'Error processing payment: ' + error.message })
  }
}

// Submit payment for ticket (after ticket is created)
const submitPayment = async (req, res) => {
  try {
    const { ticketId } = req.params
    const { amount, method, referenceId, screenshot } = req.body
    const userId = req.user.id

    // Validate required fields
    if (!referenceId) {
      return res
        .status(400)
        .json({ message: 'Payment reference ID is required' })
    }

    const ticket = await Ticket.findOne({ ticketId }).populate('event')
    if (!ticket) {
      return res.status(404).json({ message: 'Ticket not found' })
    }

    // Security: Ensure ticket belongs to user
    if (ticket.user.toString() !== userId) {
      return res
        .status(403)
        .json({ message: 'Not authorized to submit payment for this ticket' })
    }

    if (ticket.status !== 'pending') {
      return res
        .status(400)
        .json({ message: 'Ticket is not in pending status' })
    }

    // Check for existing pending payment
    const existingPayment = await Payment.findOne({
      ticket: ticket._id,
      status: 'pending',
    })

    if (existingPayment) {
      return res.status(400).json({
        message: 'Payment already submitted, waiting for verification',
        paymentId: existingPayment._id,
      })
    }

    // Create payment with PENDING status
    const payment = new Payment({
      event: ticket.event._id,
      user: ticket.user,
      ticket: ticket._id,
      amount: amount || ticket.event.price,
      method: method || 'upi',
      status: 'pending',
      referenceId,
      screenshot: screenshot || '',
    })

    await payment.save()

    // Emit to organizer
    emitToOrganizer(ticket.event.organiser.toString(), 'paymentSubmitted', {
      ticketId,
      paymentId: payment._id,
      eventId: ticket.event._id,
      amount: payment.amount,
      userId: ticket.user,
    })

    createAuditLog('PAYMENT_SUBMITTED', userId, ticket.event._id, {
      paymentId: payment._id,
      ticketId,
      amount: payment.amount,
    })

    res.status(201).json({
      success: true,
      payment,
      message: 'Payment submitted for verification',
    })
  } catch (error) {
    console.error('Submit payment error:', error)
    res.status(500).json({ message: 'Error submitting payment' })
  }
}

// Get payment status
const getPaymentStatus = async (req, res) => {
  try {
    const { orderId, ticketId } = req.params // Support both orderId (polling) and ticketId
    const userId = req.user.id

    let query = {}
    if (orderId === 'null') {
      // Legacy ticketId route
      query = { ticket: ticketId }
    } else {
      query = { razorpayOrderId: orderId }
    }

    const payment = await Payment.findOne(query)
      .populate('event', 'title date organizerUpiId')
      .populate('ticket', 'ticketId status qrCode')
      .populate('verifiedBy', 'name email')
      .sort({ createdAt: -1 })

    if (!payment) {
      return sendStandardResponse(res, false, 'Payment not found')
    }

    // Authorization
    if (payment.user.toString() !== userId) {
      const isOrganizer =
        payment.event && payment.event.organiser.toString() === userId
      if (!isOrganizer) {
        return sendStandardResponse(res, false, 'Not authorized')
      }
    }

    // Include ticket status for polling
    const ticketStatus = payment.ticket ? payment.ticket.status : null
    const isProcessing =
      !payment.webhookProcessedAt && payment.status === 'pending'

    sendStandardResponse(res, true, 'Status fetched', {
      payment,
      ticketStatus,
      isWebhookProcessing: isProcessing,
      pollingRecommended: isProcessing,
      organizerUpiId: payment.event?.organizerUpiId,
    })
  } catch (error) {
    paymentLogger.logPaymentEvent(
      'GET_STATUS_ERROR',
      req.user?.id,
      null,
      null,
      error,
    )
    sendStandardResponse(res, false, 'Error fetching status', {}, error.message)
  }
}

// Manual verification (legacy for non-Razorpay)
const manualVerifyPayment = async (req, res) => {
  try {
    const { paymentId } = req.params
    const { status, rejectionReason } = req.body
    const organizerId = req.user.id

    console.log('MANUAL VERIFY PAYMENT:', paymentId, status)

    // Validate status
    if (!status || !['verified', 'rejected'].includes(status)) {
      return res
        .status(400)
        .json({ message: 'Invalid status. Use "verified" or "rejected"' })
    }

    const payment =
      await Payment.findById(paymentId).populate('event ticket user')
    if (!payment) {
      return res.status(404).json({ message: 'Payment not found' })
    }

    // SECURITY: Verify organizer owns the event
    if (payment.event.organiser.toString() !== organizerId) {
      return res
        .status(403)
        .json({ message: 'Not authorized to verify payments for this event' })
    }

    if (payment.status !== 'pending') {
      return res.status(400).json({ message: 'Payment already processed' })
    }

    // Update payment status
    payment.status = status
    payment.verifiedBy = organizerId
    payment.verifiedAt = new Date()

    if (status === 'verified') {
      payment.markVerified(organizerId)

      // Generate QR code for ticket (ONLY NOW!)
      const qrCode = await QRCode.toDataURL(payment.ticket.ticketId, {
        width: 300,
        margin: 2,
      })

      // Update ticket to PAID and add QR code
      payment.ticket.status = 'paid'
      payment.ticket.qrCode = qrCode
      payment.ticket.paymentVerified = true
      await payment.ticket.save()

      // Update event tickets sold
      await Event.findByIdAndUpdate(payment.event._id, {
        $inc: { registered: 1 },
      })

      // Emit real-time updates
      emitToEvent(payment.event._id.toString(), 'ticketActivated', {
        ticketId: payment.ticket.ticketId,
      })

      emitToOrganizer(organizerId, 'paymentApproved', {
        ticketId: payment.ticket.ticketId,
        paymentId: payment._id,
        amount: payment.amount,
        userName: payment.user.name,
      })

      createAuditLog(
        'MANUAL_PAYMENT_VERIFIED',
        organizerId,
        payment.event._id,
        {
          paymentId: payment._id,
          ticketId: payment.ticket.ticketId,
          amount: payment.amount,
        },
      )
    } else {
      // Rejected
      payment.ticket.status = 'rejected'
      await payment.ticket.save()

      createAuditLog('PAYMENT_REJECTED', organizerId, payment.event._id, {
        paymentId: payment._id,
        reason: rejectionReason || 'Not specified',
      })
    }

    await payment.save()

    res.status(200).json({
      success: true,
      payment,
      ticket: payment.ticket,
      message:
        status === 'verified'
          ? 'Payment verified! Ticket activated.'
          : 'Payment rejected',
    })
  } catch (error) {
    console.error('Manual verify payment error:', error)
    res.status(500).json({ message: 'Error verifying payment' })
  }
}

// Get pending payments for organizer
const getPendingPayments = async (req, res) => {
  try {
    const organizerId = req.user.id

    const payments = await Payment.find({ status: 'pending' })
      .populate({
        path: 'event',
        match: { organiser: organizerId },
        select: 'title date price organiser paymentDetails',
      })
      .populate('user', 'name email')
      .populate('ticket', 'ticketId status')
      .sort({ createdAt: -1 })

    const filteredPayments = payments.filter((p) => p.event !== null)

    res.status(200).json(filteredPayments)
  } catch (error) {
    console.error('Get pending payments error:', error)
    res.status(500).json({ message: 'Error fetching pending payments' })
  }
}

// Get all payments for organizer's events
const getOrganizerPayments = async (req, res) => {
  try {
    const organizerId = req.user.id
    const { status, page = 1, limit = 20 } = req.query

    const payments = await Payment.find()
      .populate({
        path: 'event',
        match: { organiser: organizerId },
        select: 'title date price organiser',
      })
      .populate('user', 'name email')
      .populate('ticket', 'ticketId')
      .populate('verifiedBy', 'name email')
      .sort({ createdAt: -1 })
      .skip((parseInt(page) - 1) * parseInt(limit))
      .limit(parseInt(limit))

    const filteredPayments = payments.filter((p) => p.event !== null)

    let finalPayments = filteredPayments
    if (status) {
      finalPayments = filteredPayments.filter((p) => p.status === status)
    }

    const total = await Payment.countDocuments()

    res.status(200).json({
      payments: finalPayments,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        pages: Math.ceil(total / parseInt(limit)),
      },
    })
  } catch (error) {
    console.error('Get organizer payments error:', error)
    res.status(500).json({ message: 'Error fetching payments' })
  }
}

// CREATE RAZORPAY ORDER FOR UPI PAYMENT
const createPaymentOrder = async (req, res) => {
  try {
    const { eventId, quantity = 1 } = req.body
    const userId = req.user.id

    // Fetch event
    const event = await Event.findById(eventId).populate('organiser', 'name')
    if (!event) {
      return res.status(404).json({ message: 'Event not found' })
    }

    // Check capacity
    if (event.registeredCount + quantity > event.capacity) {
      return res.status(400).json({ message: 'Insufficient seats available' })
    }

    // Duplicate check
    const existingRegistration = await Ticket.findOne({
      user: userId,
      event: eventId,
      paymentStatus: { $in: ['verified', 'paid'] },
    })
    if (existingRegistration) {
      return res.status(400).json({
        message: 'You already have a verified ticket for this event',
        ticketId: existingRegistration.ticketId,
      })
    }

    const amount = Math.round(event.ticketPrice * quantity * 100) // paise

    if (amount <= 0) {
      return res.status(400).json({ message: 'Invalid amount' })
    }

    const orderData = {
      amount,
      currency: 'INR',
      receipt: `rcpt_${Date.now()}`,
      notes: {
        eventId: event._id.toString(),
        eventTitle: event.title,
        organizer: event.organiser.name,
        organizerUpiId: event.organizerUpiId, // for reference
        quantity,
      },
      partial_payment: false,
    }

    if (!razorpay) {
      return res.status(500).json({
        message: 'Payment system not configured',
      })
    }
    const razorpayOrder = await razorpay.orders.create(orderData)

    // Create pending payment record for idempotency
    console.log('Creating payment with referenceId:', `ref_${Date.now()}`)
    const payment = await Payment.create({
      event: eventId,
      user: userId,
      amount: event.ticketPrice * quantity,
      currency: 'INR',
      method: 'razorpay',
      status: 'pending',
      referenceId: `ref_${Date.now()}`,
      razorpayOrderId: razorpayOrder.id,
    })

    res.status(200).json({
      success: true,
      orderId: razorpayOrder.id,
      amount: razorpayOrder.amount / 100,
      currency: razorpayOrder.currency,
      key: process.env.RAZORPAY_KEY_ID,
      name: 'EventNest',
      description: `Ticket for ${event.title}`,
      image: event.imageUrl || 'https://eventnest.com/logo.png',
      handler: '/api/payments/verify',
      prefill: {
        name: req.user.name,
        email: req.user.email,
        contact: req.user.phone || '',
      },
      theme: {
        color: '#6366F1',
      },
      method: {
        upi: true,
        card: false,
        netbanking: false,
        wallet: true,
      },
    })
  } catch (error) {
    console.error('Create Razorpay order error:', error)
    res
      .status(500)
      .json({ message: 'Failed to create payment order', error: error.message })
  }
}

// VERIFY RAZORPAY PAYMENT SIGNATURE + CREATE TICKET + UPDATE WALLET
const verifyPayment = async (req, res) => {
  console.log('🔄 Payment verification started')
  try {
    const {
      razorpay_order_id,
      razorpay_payment_id,
      razorpay_signature,
      eventId,
      attendeeInfo,
    } = req.body
    const userId = req.user.id

    console.log('VERIFY START', req.body)
    console.log('📦 Payment verification payload:', {
      razorpay_order_id,
      razorpay_payment_id,
      eventId,
    })
    console.log('Finding payment with orderId:', razorpay_order_id)

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return res.status(400).json({ message: 'Missing Razorpay details' })
    }

    // Fetch payment record for idempotency
    const payment = await Payment.findOne({
      razorpayOrderId: razorpay_order_id,
    })
    if (!payment) {
      console.log('❌ Payment order not found')
      return res.status(404).json({ message: 'Payment order not found' })
    }

    if (payment.status !== 'pending') {
      console.log('⚠️ Payment already processed:', payment.status)
      return res.status(400).json({ message: 'Payment already processed' })
    }

    // Server-side signature verification
    const expectedSignature = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(razorpay_order_id + '|' + razorpay_payment_id)
      .digest('hex')

    console.log(
      '🔐 Signature verification:',
      expectedSignature === razorpay_signature ? '✅ VALID' : '❌ INVALID',
    )

    if (expectedSignature !== razorpay_signature) {
      console.log('❌ Invalid payment signature')
      return res.status(400).json({ message: 'Invalid payment signature' })
    }

    // Fetch Razorpay payment details
    if (!razorpay) {
      console.log('❌ Razorpay not initialized')
      return res.status(500).json({
        message: 'Payment system not configured',
      })
    }
    const razorpayPayment = await razorpay.payments.fetch(razorpay_payment_id)

    if (razorpayPayment.status !== 'captured') {
      console.log('❌ Payment not captured:', razorpayPayment.status)
      return res.status(400).json({ message: 'Payment not captured' })
    }

    if (razorpayPayment.amount !== payment.amount * 100) {
      console.log(
        '❌ Amount mismatch:',
        razorpayPayment.amount,
        'vs',
        payment.amount * 100,
      )
      return res.status(400).json({ message: 'Amount mismatch' })
    }

    console.log('VERIFY PAYMENT:', {
      paymentId: payment._id,
      referenceId: payment.referenceId,
    })
    if (!payment.referenceId) {
      payment.referenceId = `ref_${Date.now()}`
    }
    console.log('✅ Razorpay payment valid, creating ticket...')

    // Mark payment verified
    payment.razorpayPaymentId = razorpay_payment_id
    payment.razorpaySignature = razorpay_signature
    payment.status = 'verified'
    payment.completedAt = new Date()
    await payment.save()

    // Create ticket
    const event = await Event.findById(eventId)
    if (!event) {
      console.log('❌ Event not found')
      return res.status(404).json({ message: 'Event not found' })
    }

    // Check capacity (with transaction-like check)
    const registeredCount = await Ticket.countDocuments({
      event: eventId,
      paymentStatus: 'verified',
    })

    if (registeredCount >= event.capacity) {
      console.log('❌ Event capacity reached')
      return res.status(400).json({ message: 'Event capacity reached' })
    }

    // Duplicate payment protection
    const existingTicket = await Ticket.findOne({
      razorpayPaymentId: razorpay_payment_id,
    })
    if (existingTicket) {
      console.log('⚠️ Duplicate payment attempt, already verified')
      return res.status(200).json({
        success: true,
        message: 'Already verified',
        ticketId: existingTicket.ticketId,
      })
    }

    // Create registration/ticket
    const registrationData = {
      event: eventId,
      user: userId,
      paymentId: payment._id,
      amount: payment.amount,
      paymentStatus: 'verified',
      paymentMethod: 'razorpay',
      razorpayOrderId: razorpay_order_id,
      razorpayPaymentId: razorpay_payment_id,
      paymentVerified: true,
      status: 'paid',
      attendeeInfo: attendeeInfo || {},
    }

    console.log('🆕 Registration data before create:')
    console.log(JSON.stringify(registrationData, null, 2))

    let created

    try {
      created = await Ticket.create(registrationData)

      console.log('✅ Created registration result:')
      console.log(JSON.stringify(created.toObject(), null, 2))

      console.log('🎫 Generated ticketId:', created.ticketId)
    } catch (err) {
      console.error('❌ Ticket creation failed:', err.message)
      console.error(err)
      throw err // Re-throw to maintain original error handling
    }

    // Generate QR
    const qrPayload = {
      ticketId: created.ticketId,
      eventId: String(created.event),
      userId: String(created.user),
    }

    const qrCode = await generateTicketQR(qrPayload)
    created.qrCode = qrCode
    await created.save()

    // Update event counters
    await Event.findByIdAndUpdate(eventId, {
      $inc: {
        registeredCount: 1,
        registered: 1,
      },
    })

    // UPDATE ORGANIZER WALLET 💰
    const organizer = await User.findById(event.organiser)
    if (organizer && organizer.role === 'organizer') {
      const platformFee = payment.amount * 0.1 // 10% platform fee
      const organizerShare = payment.amount - platformFee

      organizer.balance += organizerShare
      await organizer.save()

      console.log(
        `💰 Wallet updated: Organizer ${organizer.name} +₹${organizerShare.toFixed(2)} (total: ₹${organizer.balance})`,
      )
    }

    // Real-time updates
    emitToOrganizer(event.organiser.toString(), 'ticketSold', {
      eventId,
      totalTicketsSold: registeredCount + 1,
      latestBuyer: req.user.name || req.user.email,
      amount: payment.amount,
      walletUpdate: true,
    })

    emitToEvent(eventId, 'ticketPurchased', {
      ticketId: created.ticketId,
      buyer: req.user.name,
    })

    console.log('✅ Payment verified, ticket created, wallet updated')

    res.status(200).json({
      success: true,
      message: 'Payment verified and ticket created',
      ticketId: created.ticketId,
      qrCode,
      paymentId: payment._id,
    })
  } catch (error) {
    console.error('❌ Verify payment error:', error)
    res.status(500).json({ message: 'Payment verification failed' })
  }
}

// Keep legacy manual verify for non-Razorpay flows
exports.manualVerifyPayment = async (req, res) => {
  try {
    // Example legacy verification logic (can expand later)
    const { paymentId } = req.params

    if (!paymentId) {
      return res.status(400).json({
        success: false,
        message: 'Payment ID required',
      })
    }

    // Legacy manual verification placeholder
    // Organizer/admin can verify manually later

    return res.status(200).json({
      success: true,
      message: 'Legacy manual verification successful',
      paymentId,
    })
  } catch (error) {
    console.error('Manual verification error:', error)

    res.status(500).json({
      success: false,
      message: 'Manual verification failed',
    })
  }
}

// Handle webhook
const handleWebhook = async (req, res) => {
  const webhookVerified = req.webhookVerified
  const eventId = req.eventId

  if (!webhookVerified) {
    return sendStandardResponse(res, false, 'Webhook not verified')
  }

  try {
    const razorpayEvent = req.body.event
    const razorpayEntity = req.body.entity

    paymentLogger.logWebhook(eventId, true, `Processing ${razorpayEvent}`)

    if (razorpayEvent !== 'payment.captured') {
      return sendStandardResponse(res, true, `Event ${razorpayEvent} ignored`, {
        eventId,
      })
    }

    // Find payment by Razorpay payment ID
    const razorpayPaymentId = razorpayEntity.id
    const payment = await Payment.findOne({ razorpayPaymentId })

    if (!payment) {
      return sendStandardResponse(res, false, 'Payment not found')
    }

    if (payment.webhookProcessedAt) {
      await createAuditLog(
        'WEBHOOK_DUPLICATE',
        null,
        payment.event,
        {
          webhookEventId: eventId,
          paymentId: payment._id,
          alreadyProcessedAt: payment.webhookProcessedAt,
        },
        payment._id,
      )
      return sendStandardResponse(res, true, 'Already processed')
    }

    // Atomic update with webhook idempotency
    const session = await mongoose.startSession()
    await session.withTransaction(async () => {
      // Double-check status
      const updatedPayment = await Payment.findById(payment._id).session(
        session,
      )
      if (updatedPayment.status !== 'pending') {
        throw new Error('Payment not pending')
      }

      // Mark webhook processed + update status
      updatedPayment.status = 'verified'
      updatedPayment.webhookEventId = eventId
      updatedPayment.webhookProcessedAt = new Date()
      updatedPayment.processedAt = new Date()
      updatedPayment.completedAt = new Date()
      await updatedPayment.save({ session })

      // Check capacity atomically
      const registeredCount = await Ticket.countDocuments({
        event: payment.event,
        paymentStatus: 'verified',
      }).session(session)

      const eventDoc = await Event.findById(payment.event).session(session)
      if (registeredCount >= eventDoc.capacity) {
        throw new Error('Event full')
      }

      // Create ticket (auto-sync via pre-save hook)
      const registration = new Ticket({
        event: payment.event,
        user: payment.user,
        paymentId: payment._id,
        amount: payment.amount,
        paymentStatus: 'verified',
        paymentMethod: 'razorpay',
        razorpayPaymentId: razorpayPaymentId,
        razorpayOrderId: payment.razorpayOrderId,
        attendeeInfo: {},
      })
      await registration.save({ session })

      // Generate QR
      const qrPayload = {
        ticketId: registration.ticketId,
        eventId: String(payment.event),
        userId: String(payment.user),
      }
      const qrCode = await generateTicketQR(qrPayload)
      registration.qrCode = qrCode
      await registration.save({ session })

      // Atomic event counter update
      await Event.findByIdAndUpdate(
        payment.event,
        { $inc: { registeredCount: 1, registered: 1 } },
        { session },
      )

      // Audit & sockets
      await createAuditLog(
        'TICKET_WEBHOOK_CREATED',
        payment.user,
        payment.event,
        {
          webhookEventId: eventId,
          paymentId: payment._id,
          ticketId: registration.ticketId,
          eventType: 'payment.captured',
        },
        payment._id,
      )

      emitToEvent(String(payment.event), 'ticketCreated', {
        ticketId: registration.ticketId,
        webhookEventId: eventId,
      })
      emitToOrganizer(eventDoc.organiser.toString(), 'paymentCaptured', {
        paymentId: payment._id,
        ticketId: registration.ticketId,
        amount: payment.amount,
      })
    })

    await createAuditLog('WEBHOOK_SUCCESS', null, null, {
      webhookEventId: eventId,
      razorpayPaymentId,
      status: 'completed',
    })

    sendStandardResponse(res, true, 'Payment captured & ticket created')
  } catch (error) {
    paymentLogger.logWebhook(eventId, false, 'processing_failed', error)
    await createAuditLog('WEBHOOK_FAILED', null, null, {
      webhookEventId: eventId,
      error: error.message,
    })
    sendStandardResponse(
      res,
      false,
      'Webhook processing failed',
      {},
      error.message,
    )
  }
}

// Get user's payment history
const getMyPayments = async (req, res) => {
  try {
    const userId = req.user.id

    const payments = await Payment.find({ user: userId })
      .populate('event', 'title date location')
      .populate('verifiedBy', 'name email')
      .sort({ createdAt: -1 })

    res.status(200).json(payments)
  } catch (error) {
    console.error('Get my payments error:', error)
    res.status(500).json({ message: 'Error fetching payments' })
  }
}

// Request refund
const requestRefund = async (req, res) => {
  try {
    const { registrationId } = req.params
    const userId = req.user.id

    const ticket = await Ticket.findById(registrationId)
    if (!ticket) {
      return res.status(404).json({ message: 'Registration not found' })
    }

    if (ticket.user.toString() !== userId) {
      return res.status(403).json({ message: 'Not authorized' })
    }

    if (ticket.status !== 'paid') {
      return res
        .status(400)
        .json({ message: 'Only paid tickets can be refunded' })
    }

    const payment = await Payment.findOne({ ticket: ticket._id })
    if (payment) {
      payment.status = 'refund_requested'
      await payment.save()
    }

    ticket.status = 'refund_requested'
    await ticket.save()

    createAuditLog('REFUND_REQUESTED', userId, ticket.event, {
      ticketId: ticket.ticketId,
      paymentId: payment?._id,
    })

    res.status(200).json({
      success: true,
      message: 'Refund requested successfully',
    })
  } catch (error) {
    console.error('Request refund error:', error)
    res.status(500).json({ message: 'Error requesting refund' })
  }
}

// Get audit logs
const getAuditLogs = async (req, res) => {
  try {
    const { page = 1, limit = 50 } = req.query
    const skip = (parseInt(page) - 1) * parseInt(limit)

    const logs = await PaymentAudit.find({})
      .populate('eventId', 'title')
      .populate('userId', 'name email')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit))

    const total = await PaymentAudit.countDocuments({})

    res.status(200).json({
      logs,
      total,
      page: parseInt(page),
      pages: Math.ceil(total / parseInt(limit)),
    })
  } catch (error) {
    console.error('Get audit logs error:', error)
    res.status(500).json({ message: 'Error fetching audit logs' })
  }
}

module.exports = {
  submitPaymentProof,
  processPayment,
  submitPayment,
  getPaymentStatus,
  verifyPayment,
  manualVerifyPayment,
  getPendingPayments,
  getOrganizerPayments,
  createPaymentOrder,
  handleWebhook,
  getMyPayments,
  requestRefund,
  getAuditLogs,
}
